var shujvyuan = {
      first:function () {
        var LAreaData=[{
          "code":"1",
          "region":"京",
          "add":"北京"
        },{
          "code":"1",
          "region":"津",
          "add":"天津"
        },{
          "code":"1",
          "region":"冀",
          "add":"河北"
        },{
          "code":"1",
          "region":"晋",
          "add":"山西"
        },{
          "code":"1",
          "region":"蒙",
          "add":"内蒙古"
        },{
          "code":"1",
          "region":"辽",
          "add":"辽宁"
        },{
          "code":"1",
          "region":"吉",
          "add":"吉林"
        },{
          "code":"1",
          "region":"黑",
          "add":"黑龙江"
        },{
          "code":"2",
          "region":"沪",
          "add":"上海"
        },{
          "code":"1",
          "region":"苏",
          "add":"江苏"
        },{
          "code":"1",
          "region":"浙",
          "add":"浙江"
        },{
          "code":"1",
          "region":"皖",
          "add":"安徽"
        },{
          "code":"1",
          "region":"闽",
          "add":"福建"
        },{
          "code":"1",
          "region":"赣",
          "add":"江西"
        },{
          "code":"1",
          "region":"鲁",
          "add":"山东"
        },{
          "code":"1",
          "region":"豫",
          "add":"河南"
        },{
          "code":"1",
          "region":"鄂",
          "add":"湖北"
        },{
          "code":"1",
          "region":"湘",
          "add":"湖南"
        },{
          "code":"1",
          "region":"粤",
          "add":"广东"
        },{
          "code":"1",
          "region":"桂",
          "add":"广西"
        },{
          "code":"1",
          "region":"琼",
          "add":"海南"
        },{
          "code":"1",
          "region":"渝",
          "add":"重庆"
        },{
          "code":"1",
          "region":"川",
          "add":"四川"
        },{
          "code":"1",
          "region":"贵",
          "add":"贵州"
        },{
          "code":"1",
          "region":"云",
          "add":"云南"
        },{
          "code":"1",
          "region":"藏",
          "add":"西藏"
        },{
          "code":"1",
          "region":"陕",
          "add":"陕西"
        },{
          "code":"1",
          "region":"甘",
          "add":"甘肃"
        },{
          "code":"1",
          "region":"青",
          "add":"青海"
        },{
          "code":"1",
          "region":"宁",
          "add":"宁夏"
        },{
          "code":"1",
          "region":"新",
          "add":"新疆"
        },{
          "code":"1",
          "region":"台",
          "add":"台湾"
        },{
          "code":"1",
          "region":"港",
          "add":"香港"
        },{
          "code":"1",
          "region":"澳",
          "add":"澳门"
        }];
        return LAreaData
      },
  forth:function () {
      var list = [{
        "name":"1"
      },{
        "name":"2"
      },{
        "name":"3"
      },{
        "name":"4"
      },{
        "name":"5"
      },{
        "name":"6"
      },{
        "name":"7"
      },{
        "name":"8"
      },{
        "name":"9"
      },{
        "name":"0"
      }]
    return list;
  },
  fifth:function () {
    var list = {
       "first":[{
         "name":"Q"
       },{
         "name":"W"
       },{
         "name":"E"
       },{
         "name":"R"
       },{
         "name":"T"
       },{
         "name":"Y"
       },{
         "name":"U"
       },{
         "name":"I"
       },{
         "name":"O"
       },{
         "name":"P"
       }],
      "second":[{
        "name":"A"
      },{
        "name":"S"
      },{
        "name":"D"
      },{
        "name":"F"
      },{
        "name":"G"
      },{
        "name":"H"
      },{
        "name":"J"
      },{
        "name":"K"
      },{
        "name":"L"
      }],
      "third":[{
        "name":"Z"
      },{
        "name":"X"
      },{
        "name":"C"
      },{
        "name":"V"
      },{
        "name":"B"
      },{
        "name":"N"
      },{
        "name":"M"
      }]
    }
    return list;
  },
  sixth:function () {
    var list = [{
       name:"普货险",
       number:12000,
       img:require("../images/veer-134703036.jpg"),
       price:123
    },{
      name:"鲜货险",
      number:1200,
      img:require("../images/veer-159279785.jpg"),
      price:123
    },{
      name:"易碎品险",
      number:12000,
      img:require("../images/veer-134703036.jpg"),
      price:1243
    },{
      name:"生命安全险",
      number:12000,
      img:require("../images/veer-134703036.jpg"),
      price:1
    },{
      name:"车险",
      number:12000,
      img:require("../images/veer-134703036.jpg"),
      price:123
    },{
      name:"危险品险",
      number:12000,
      img:require("../images/veer-159282503.jpg"),
      price:123
    },{
      name:"人险",
      number:12000,
      img:require("../images/veer-159279785.jpg"),
      price:123
    },{
      name:"冷链险",
      number:12000,
      img:require("../images/veer-316360254.jpg"),
      price:1233
    },{
      name:"轮胎险",
      number:12000,
      img:require("../images/veer-159282503.jpg"),
      price:1232
    },{
      name:"牛险",
      number:12000,
      img:require("../images/veer-159282503.jpg"),
      price:122223
    },{
      name:"老满险",
      number:12000,
      img:require("../images/veer-159282503.jpg"),
      price:12224423
    }]
    return list;
  }
}
export {
  shujvyuan
}
